
const PASS = 'Todocasero.2020';
function login(){ const p=document.getElementById('pass').value; if(p===PASS){document.getElementById('login').classList.add('hidden'); document.getElementById('panel').classList.remove('hidden'); localStorage.setItem('hu_admin','1'); cargarAdmin(); } else {document.getElementById('loginError').classList.remove('hidden');} }
function logout(){localStorage.removeItem('hu_admin'); location.reload();}
if(localStorage.getItem('hu_admin')==='1'){document.getElementById('login').classList.add('hidden'); document.getElementById('panel').classList.remove('hidden'); setTimeout(cargarAdmin,200);}
function showTab(id){document.querySelectorAll('.tab').forEach(t=>t.classList.add('hidden')); document.getElementById('tab-'+id).classList.remove('hidden'); document.querySelectorAll('.tabBtn').forEach(b=>b.classList.remove('bg-slate-900','text-white')); document.querySelectorAll('.tabBtn').forEach(b=>b.classList.add('bg-white')); event.target.classList.add('bg-slate-900','text-white');}

function cargarAdmin(){
  const cfg=JSON.parse(localStorage.getItem('hu_config')||'null') || {nombreIglesia:"Hermanos Unidos",subtitulo:"Una familia en Cristo",heroTitulo:"Bienvenidos a Casa. Dios te está esperando.",heroSub:"Iglesia virtual para toda Argentina.",alias:"maxinaranja2025",radioNombre:"Radio Hermanos Unidos 24/7",metaDon:500000,devTitulo:"Dios renueva tus fuerzas",devTexto:"Pero los que esperan a Jehová tendrán nuevas fuerzas...",waMensaje:"Bendecido día {nombre} 🙏"};
  document.getElementById('cfgNombre').value=cfg.nombreIglesia; document.getElementById('cfgSub').value=cfg.subtitulo; document.getElementById('cfgHeroTitulo').value=cfg.heroTitulo; document.getElementById('cfgHeroSub').value=cfg.heroSub; document.getElementById('cfgDevTitulo').value=cfg.devTitulo; document.getElementById('cfgDevTexto').value=cfg.devTexto; document.getElementById('cfgRadioNombre').value=cfg.radioNombre; document.getElementById('cfgAlias').value=cfg.alias; document.getElementById('cfgMeta').value=cfg.metaDon; document.getElementById('cfgWAMsg').value=cfg.waMensaje;
  document.getElementById('cfgColor1').value=cfg.colorPrimario||'#FF6900'; document.getElementById('cfgColor2').value=cfg.colorSecundario||'#0F172A';

  const pred=JSON.parse(localStorage.getItem('hu_predicas')||'[]'); document.getElementById('listaPredicasAdmin').innerHTML=pred.map(p=>`<div class="flex justify-between border-b py-2 text-xs"><div><b>${p.titulo}</b> [${p.cat}] - ${p.pastor}<br>${p.texto.substring(0,80)}...</div><button onclick="borrarPredica(${p.id})" class="text-red-600 font-bold">X</button></div>`).join('');
  const vids=JSON.parse(localStorage.getItem('hu_videos')||'[]'); document.getElementById('listaVideosAdmin').innerHTML=vids.map(v=>`<div class="flex justify-between border-b py-2 text-xs"><span>${v.titulo} - ${v.yt}</span><button onclick="borrarVideo(${v.id})" class="text-red-600">X</button></div>`).join('');
  const testi=JSON.parse(localStorage.getItem('hu_testi')||'[]'); document.getElementById('listaTestiAdmin').innerHTML=testi.map(t=>`<div class="flex justify-between border-b py-2 text-xs"><span><b>${t.nombre}</b> ${t.prov}: ${t.texto.substring(0,60)}</span><button onclick="borrarTesti(${t.id})" class="text-red-600">X</button></div>`).join('');
  const sedes=JSON.parse(localStorage.getItem('hu_sedes')||'[]'); document.getElementById('listaSedesAdmin').innerHTML=sedes.map(s=>`<div class="flex justify-between border-b py-2 text-xs"><span><b>${s.prov}</b> - ${s.dir} - ${s.hor} - WA:${s.wa}</span><button onclick="borrarSede(${s.id})" class="text-red-600">X</button></div>`).join('');
  const play=JSON.parse(localStorage.getItem('hu_playlist')||'[]'); document.getElementById('listaPlaylistAdmin').innerHTML=play.map(p=>`<div class="flex justify-between border-b py-2 text-xs"><span>${p.titulo} - ${p.yt}</span><button onclick="borrarMusica(${p.id})" class="text-red-600">X</button></div>`).join('');

  const wa=JSON.parse(localStorage.getItem('hu_wa')||'[]'); document.getElementById('tablaWA').innerHTML='<table class="w-full"><tr class="bg-slate-100"><th>Nombre</th><th>WhatsApp</th><th>Fecha</th></tr>'+wa.map(w=>`<tr class="border-b"><td class="p-1">${w.nombre}</td><td class="p-1">${w.numero}</td><td class="p-1">${w.fecha}</td></tr>`).join('')+'</table>';
  const ora=JSON.parse(localStorage.getItem('hu_oraciones')||'[]'); document.getElementById('tablaOraciones').innerHTML=ora.map(o=>`<div class="p-2 border-b"><b>${o.nombre}</b> (${o.fecha}): ${o.texto}</div>`).join('');
  document.getElementById('statVisitas').innerText=localStorage.getItem('hu_visitas')||0; document.getElementById('statWA').innerText=wa.length; document.getElementById('statOra').innerText=ora.length;
  const rec=parseInt(localStorage.getItem('hu_recaudado')||'0'); document.getElementById('statDon').innerText='$'+rec.toLocaleString(); document.getElementById('recaudadoAdmin').innerText=rec.toLocaleString(); document.getElementById('metaAdmin').innerText=(cfg.metaDon||500000).toLocaleString(); document.getElementById('barraAdmin').style.width=Math.min(100,rec/(cfg.metaDon||500000)*100)+'%';
}

function getCfg(){ return JSON.parse(localStorage.getItem('hu_config')||'{}'); }
function saveCfg(c){ localStorage.setItem('hu_config', JSON.stringify(c)); }

function guardarGeneral(){ let c=getCfg(); c.nombreIglesia=document.getElementById('cfgNombre').value; c.subtitulo=document.getElementById('cfgSub').value; c.colorPrimario=document.getElementById('cfgColor1').value; c.colorSecundario=document.getElementById('cfgColor2').value; saveCfg(c); alert('Guardado General ✅'); }
function guardarHero(){ let c=getCfg(); c.heroTitulo=document.getElementById('cfgHeroTitulo').value; c.heroSub=document.getElementById('cfgHeroSub').value; c.devTitulo=document.getElementById('cfgDevTitulo').value; c.devTexto=document.getElementById('cfgDevTexto').value; saveCfg(c); alert('Hero guardado ✅'); }
function guardarRadio(){ let c=getCfg(); c.radioNombre=document.getElementById('cfgRadioNombre').value; saveCfg(c); alert('Radio guardado ✅'); }
function guardarDonaciones(){ let c=getCfg(); c.alias=document.getElementById('cfgAlias').value; c.metaDon=parseInt(document.getElementById('cfgMeta').value)||500000; saveCfg(c); alert('Donaciones guardado ✅'); }
function guardarWA(){ let c=getCfg(); c.waMensaje=document.getElementById('cfgWAMsg').value; saveCfg(c); alert('Mensaje WA guardado ✅'); }

function agregarPredicaAdmin(){ const t=document.getElementById('editPredTitulo').value; const cat=document.getElementById('editPredCat').value; const txt=document.getElementById('editPredTexto').value; const pas=document.getElementById('editPredPastor').value||'Hermanos Unidos'; if(!t||!txt){alert('Falta título o texto');return;} let pred=JSON.parse(localStorage.getItem('hu_predicas')||'[]'); pred.unshift({id:Date.now(),titulo:t,cat,texto:txt,pastor:pas}); localStorage.setItem('hu_predicas', JSON.stringify(pred)); cargarAdmin(); document.getElementById('editPredTitulo').value=''; document.getElementById('editPredTexto').value=''; }
function borrarPredica(id){let p=JSON.parse(localStorage.getItem('hu_predicas')||'[]'); p=p.filter(x=>x.id!==id); localStorage.setItem('hu_predicas', JSON.stringify(p)); cargarAdmin();}
function agregarVideoAdmin(){ const t=document.getElementById('editVidTitulo').value; const yt=document.getElementById('editVidYoutube').value; if(!t||!yt){alert('Falta');return;} let v=JSON.parse(localStorage.getItem('hu_videos')||'[]'); v.unshift({id:Date.now(),titulo:t,yt,vistas:'0'}); localStorage.setItem('hu_videos', JSON.stringify(v)); cargarAdmin(); document.getElementById('editVidTitulo').value=''; document.getElementById('editVidYoutube').value=''; }
function borrarVideo(id){let v=JSON.parse(localStorage.getItem('hu_videos')||'[]'); v=v.filter(x=>x.id!==id); localStorage.setItem('hu_videos', JSON.stringify(v)); cargarAdmin();}
function agregarTestimonioAdmin(){ const n=document.getElementById('adminTNombre').value; const pr=document.getElementById('adminTProv').value; const tx=document.getElementById('adminTTexto').value; if(!n||!tx){alert('Falta');return;} let t=JSON.parse(localStorage.getItem('hu_testi')||'[]'); t.unshift({id:Date.now(),nombre:n,prov:pr||'Argentina',texto:tx}); localStorage.setItem('hu_testi', JSON.stringify(t)); cargarAdmin(); document.getElementById('adminTNombre').value=''; document.getElementById('adminTProv').value=''; document.getElementById('adminTTexto').value=''; }
function borrarTesti(id){let t=JSON.parse(localStorage.getItem('hu_testi')||'[]'); t=t.filter(x=>x.id!==id); localStorage.setItem('hu_testi', JSON.stringify(t)); cargarAdmin();}
function agregarSede(){ const prov=document.getElementById('sedeProv').value; const dir=document.getElementById('sedeDir').value; const hor=document.getElementById('sedeHor').value; const wa=document.getElementById('sedeWa').value; if(!prov){alert('Falta provincia');return;} let s=JSON.parse(localStorage.getItem('hu_sedes')||'[]'); s.push({id:Date.now(),prov,dir,hor,wa}); localStorage.setItem('hu_sedes', JSON.stringify(s)); cargarAdmin(); document.getElementById('sedeProv').value=''; document.getElementById('sedeDir').value=''; document.getElementById('sedeHor').value=''; document.getElementById('sedeWa').value=''; }
function borrarSede(id){let s=JSON.parse(localStorage.getItem('hu_sedes')||'[]'); s=s.filter(x=>x.id!==id); localStorage.setItem('hu_sedes', JSON.stringify(s)); cargarAdmin();}
function agregarMusica(){ const tit=document.getElementById('playTitulo').value; const yt=document.getElementById('playYT').value; if(!tit||!yt){alert('Falta');return;} let p=JSON.parse(localStorage.getItem('hu_playlist')||'[]'); p.push({id:Date.now(),titulo:tit,yt}); localStorage.setItem('hu_playlist', JSON.stringify(p)); cargarAdmin(); document.getElementById('playTitulo').value=''; document.getElementById('playYT').value=''; }
function borrarMusica(id){let p=JSON.parse(localStorage.getItem('hu_playlist')||'[]'); p=p.filter(x=>x.id!==id); localStorage.setItem('hu_playlist', JSON.stringify(p)); cargarAdmin();}
function sumarDonacion(){const m=parseInt(document.getElementById('montoDon').value||0); let r=parseInt(localStorage.getItem('hu_recaudado')||'0'); r+=m; localStorage.setItem('hu_recaudado', r); cargarAdmin();}
function resetDonaciones(){if(confirm('Resetear donaciones?')){localStorage.setItem('hu_recaudado','0'); cargarAdmin();}}
function exportarWA(){const wa=JSON.parse(localStorage.getItem('hu_wa')||'[]'); if(!wa.length){alert('No hay suscriptos');return;} let csv='Nombre,WhatsApp,Fecha\n'+wa.map(w=>`${w.nombre},${w.numero},${w.fecha}`).join('\n'); let blob=new Blob([csv],{type:'text/csv'}); let a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='suscriptos_hermanos_unidos.csv'; a.click();}
function copiarNumeros(){const wa=JSON.parse(localStorage.getItem('hu_wa')||'[]'); const nums=wa.map(w=>w.numero).join(', '); navigator.clipboard.writeText(nums); alert('Copiados '+wa.length+' números');}
function borrarWA(){if(confirm('Borrar todos?')){localStorage.setItem('hu_wa','[]'); cargarAdmin();}}
